"""User currency, Alerts

Revision ID: 0002_currency_alerts
Revises: 0001_initial
Create Date: 2026-05-09 16:52:30.825892

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = '0002_currency_alerts'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('trigger_above', sa.Boolean(), nullable=False),
    sa.Column('is_armed', sa.Boolean(), nullable=False),
    sa.Column('last_triggered', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.username'], name=op.f('fk_alert_user_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert'))
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_user'), ['user'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('apprise_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('apprise_url')
        batch_op.drop_column('currency')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_user'))
        batch_op.drop_index(batch_op.f('ix_alert_ticker'))

    op.drop_table('alert')
    # ### end Alembic commands ###

