"""Notes and Actionable Alerts

Revision ID: 0004_add_notes_and_actionable_to_alert
Revises: 0003_user_dark
Create Date: 2026-05-31 21:31:26.248454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0004_add_notes_and_actionable_to_alert'
down_revision = '0003_user_dark'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('actionable', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('actionable')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###

