"""Earnings Notify toggle

Revision ID: 0005_add_earnings_notify_to_user
Revises: 0004_add_notes_and_actionable_to_alert
Create Date: 2026-05-31 21:48:50.356325

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0005_add_earnings_notify_to_user'
down_revision = '0004_add_notes_and_actionable_to_alert'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earnings_notify', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('earnings_notify')

    # ### end Alembic commands ###

